[package]

version = "0.0.1"
title = "ZHA Robot Ext"
description = "ZHA Robot extension template based on python."
readme  = "docs/README.md"
authors = ["Ling.Mao@zaha-hadid.com"]

# URL of the extension source repository.
repository = " "

# One of categories for UI.
category = "robot"

# Keywords for the extension
keywords = ["architecture", "robot", "Hot wire cutting"]

# Icon to show in the extension manager
icon = "data/zaha.png"

# Preview to show in the extension manager
preview_image = " "


# Use omni.ui to build simple UI

[dependencies]
"omni.ui" = {}
"omni.kit.menu.utils" = {}
"omni.kit.window.popup_dialog" = {}

# Main python module this extension provides.
[[python.module]]
name = "zha.robot"

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test",
]
